### ISSUE TITLE
Problems on Noetic

### ISSUE THREAD

**Issue by MoscowskyAnton** [ros-visualization/rqt_tf_tree#22]
Hi! When I try to start rqt_tf_tree with common command
`rosrun rqt_tf_tree rqt_tf_tree`
I got that error
`/usr/bin/env: ‘python’: No such file or directory`
Seems package should be build with python3, but how to do that?
Thanks for any help!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by MoscowskyAnton** [comment]
Sorry about that, I though if program can't run it is a bug.
BTW I fixed that problem my downloading source and adding to CMakeLists file 
`if ("$ENV{ROS_DISTRO}" STREQUAL "noetic")
catkin_install_python(PROGRAMS
    scripts/rqt_tf_tree    
    DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
endif()`

**Comment by dirk-thomas** [comment]
The current code on master already contains a `catkin_install_python()` call. See #21.

**Comment by dirk-thomas** [comment]
I made a new Noetic release (0.6.2) which makes the already merged fix available in the binary package.
