### ISSUE TITLE
Release for Rolling and Humble

### ISSUE THREAD

**Issue by SammyRamone** [ros-visualization/rqt_tf_tree#42]
Currently this package is not released for rolling and humble.
I just tested the humble branch with Ubuntu 22.04 Rolling and it works.

**Comment by Flova** [comment]
I am also looking forward to a rolling release.

**Comment by arne48** [comment]
Hello @audrow, @wjwwood, @clalancette I am sorry, but I need help from one of you guys again.
I have already prepared and tested everything for the release of the humble and rolling branch for rqt_tf_tree.
Unfortunately, I now noticed that I already got access the release repository of ROS1 but not yet for ROS2.
Could you please give me "Maintain" permissions for ros2-gbp/rqt_tf_tree-release so that I can release the newest versions for the new distributions?
Thank you very much in advance for your help :)

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-humble-sync-2022-08-17/26882/2

**Comment by mikeferguson** [comment]
@arne48 the best bet for getting access to a ROS2 gbp repo is probably to open an issue/PR over at https://github.com/ros2-gbp/ros2-gbp-github-org - which is how the permissions are automatically configured

**Comment by arne48** [comment]
@mikeferguson Thank you very much for this helpful information.
I will open an issue about the permissions for the ros2-gbp/rqt_tf_tree-release repository. :)

**Comment by arne48** [comment]
Thank you very much everyone.
I just bloomed the newest version for humble.
If everything goes as planned it will be available soon.
